[build]
  base = "docs/"
  ignore = "git diff --quiet 'HEAD^' HEAD ."
  publish = "_site"
  command = "exe/build"

[[plugins]]
  package = "netlify-plugin-cache"
    [plugins.inputs]
    # Optional (but highly recommended). Defaults to [".cache"].
    paths = [".jekyll-metadata", ".jekyll-cache"]

[[plugins]]
  package = "netlify-plugin-debug-cache"
