#!/usr/bin/env bash

set -e

if which overmind >/dev/null; then
  overmind start -f Procfile.dev
else
  echo "Install overmind or modify exe/dev to use a different Procfile launcher."
  echo "https://github.com/DarthSim/overmind"
fi
