// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Bx:bxSun': typeof import('~icons/bx/bx-sun')['default']
    DarkModeSwitch: typeof import('./components/DarkModeSwitch.vue')['default']
    ExternalLink: typeof import('./components/ExternalLink.vue')['default']
    NavBarActions: typeof import('./components/NavBarActions.vue')['default']
    NavBarIcon: typeof import('./components/NavBarIcon.vue')['default']
    'Octicon:linkExternal16': typeof import('~icons/octicon/link-external16')['default']
  }
}
