# frozen_string_literal: true

source 'https://rubygems.org'

gemspec path: '..'

gem 'jekyll', '>= 4.3'
gem 'kramdown-parser-gfm', '~> 1.1'

group :development, :test do
  gem 'rubocop', '~> 1.9'
  gem 'rubocop-minitest', '~> 0.10'
  gem 'rubocop-performance', '~> 1.9'
end
