name: build

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [
          "2.7",
          "3.0",
          "3.1"
        ]
        gemfile: [
          "gemfiles/Gemfile-jekyll-github",
          "gemfiles/Gemfile-jekyll.4.2.x",
        ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.4
          run_install: |
            - recursive: false
            - cwd: 'docs'

      - name: Setup Code Climate test-reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: RSpec
        run: bin/rspec

      - name: Upload code coverage to Code Climate
        if: ${{ contains(github.ref, 'main') }}
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}
